<div class="highlight">
<pre>
<span class="brkt">(</span><span class="func">defun</span> AddPointGroup <span class="brkt">(</span>strName <span class="func">/</span> objGroup objGroups<span class="brkt">)</span>
  <span class="brkt">(</span><span class="func">if</span> <span class="brkt">(</span><span class="func">and</span> <span class="brkt">(</span><span class="func">setq</span> objGroups <span class="brkt">(</span><span class="func">vlax-get-property</span> <span class="brkt">(</span>op:c3ddoc<span class="brkt">)</span> <span class="quot">'</span>PointGroups<span class="brkt">))</span>
	   <span class="brkt">(</span><span class="func">setq</span> objGroup <span class="brkt">(</span>addorgetitem objGroups strName<span class="brkt">))</span>
      <span class="brkt">)</span>
    objGroup
  <span class="brkt">)</span>
<span class="brkt">)</span>
</pre>
</div>